///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSiOSMFApp.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnablingDisabling recording.
    /// </summary>
    [TestModule("8d1718bb-4dde-4c27-ba99-922b50b4261d", ModuleType.Recording, 1)]
    public partial class EnablingDisabling : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSiOSMFApp.STSiOSMFAppRepository repository.
        /// </summary>
        public static STSiOSMFApp.STSiOSMFAppRepository repo = STSiOSMFApp.STSiOSMFAppRepository.Instance;

        static EnablingDisabling instance = new EnablingDisabling();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnablingDisabling()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnablingDisabling Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Press the settings icon
            Report.Log(ReportLevel.Info, "Section", "Step## Press the settings icon", new RecordItemIndex(0));
            
            TapOnRightButton("Tap on Settings icon");
            Delay.Milliseconds(0);
            
            // Validation## Setting screen is opened. Usage statistics toggle is activated (ON) by default.
            Report.Log(ReportLevel.Info, "Section", "Validation## Setting screen is opened. Usage statistics toggle is activated (ON) by default.", new RecordItemIndex(2));
            
            VerifyActionBarTitle("Settings");
            Delay.Milliseconds(0);
            
            ValidateUsageStatistics(ValueConverter.ArgumentFromString<bool>("isON", "True"));
            Delay.Milliseconds(0);
            
            // Step## Turn the toggle OFF
            Report.Log(ReportLevel.Info, "Section", "Step## Turn the toggle OFF", new RecordItemIndex(5));
            
            SwitchUsageStatistics(ValueConverter.ArgumentFromString<bool>("on", "False"));
            Delay.Milliseconds(0);
            
            // Validation## The tracking is deactivated. The toggle is set to off state
            Report.Log(ReportLevel.Info, "Section", "Validation## The tracking is deactivated. The toggle is set to off state", new RecordItemIndex(7));
            
            ValidateUsageStatistics(ValueConverter.ArgumentFromString<bool>("isON", "False"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
