///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

using AppLayer;
using AppLayer.AppiumService;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.iOS;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Appium.Service;
using System.Linq;

namespace STSiOSMFApp.TC
{
	public partial class TabDeletingCompleteAudiogram:CommonHelper
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void VerifyTextHighlighted(string objectName)
        {
        	//Logger.logWarn("Information has to be added to identify highlighted text");
			var size=Accessor.getDriver().Manage().Window.Size;
			int starty = (int) (size.Height * 0.50);
			int endy = (int) (size.Height*0.20);
			int startx = size.Width / 2;
			int count=0;
			while(count!=3 && (!KeywordImplementation.waitForObjectExist(By.Name(objectName),TimeSpan.FromSeconds(1))))
			{
				((AndroidDriver<OpenQA.Selenium.Appium.Android.AndroidElement>)Accessor.getDriver()).Swipe(startx, starty, startx, endy, 500);
				count++;
			}
			if(KeywordImplementation.UIObject(By.Id("Active Step")).GetAttribute("value").Equals(objectName,StringComparison.CurrentCultureIgnoreCase))
				Logger.logSuccess(string.Format("'{0}' is highlighted",objectName));
			else
				Logger.logFailure(string.Format("'{0}'is not highlighted",objectName));
        }

        public void TapOnTrashToolTip()
        {
			KeywordImplementation.Click(By.Id("Trash"));
        }

        public void TapOnOverviewScreen()
        {
//			if(side.Equals("right",StringComparison.CurrentCultureIgnoreCase))
//				KeywordImplementation.Click(By.Id("Layout_Monaural_Audiogram"));
//			else if(side.Equals("left",StringComparison.CurrentCultureIgnoreCase))
//				KeywordImplementation.Click(By.Id("AudiogramGrid_LeftEar"));
        	KeywordImplementation.Click(By.Id("Layout_Monaural_Audiogram"));
        }

        public void ValidateAudiogramPointsOnCustomerOverviewScreen(string side, string points, bool isExist)
        {
        //	Logger.logWarn("Aaudiogram point summary has to be added  in Audiogram Layout object field for verification");
        	
			if(isExist)
			{
				var size=Accessor.getDriver().Manage().Window.Size;
				int starty = (int) (size.Height * 0.50);
				int endy = (int) (size.Height*0.80);
				int startx = size.Width / 2;
				((AndroidDriver<OpenQA.Selenium.Appium.Android.AndroidElement>)Accessor.getDriver()).Swipe(startx, starty, startx, endy, 1000);
				
				IWebElement audiogramGrid=null;
				if(side.Equals("right",StringComparison.CurrentCultureIgnoreCase))
					audiogramGrid=KeywordImplementation.UIObject(By.Id("AudiogramGrid_RightEar"));
				else if(side.Equals("left",StringComparison.CurrentCultureIgnoreCase))
					audiogramGrid=KeywordImplementation.UIObject(By.Id("AudiogramGrid_LeftEar"));
				
				if(audiogramGrid.GetAttribute("label").Contains(points))
					Logger.logSuccess("Audiogram point validation passed on customer overview screen");
				else
					Logger.logFailure("Audiogram point validation failed on customer overview scxreen",true);
			}
			else
			{
				Logger.logInfo(string.Format("'{0}' side audiogram points does not exist in customer overview screen",side));
			}
        }
    }
}
