///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSmyHearing.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConsentStatement recording.
    /// </summary>
    [TestModule("b65c2669-3cc3-4a6f-861b-a5336c24a96e", ModuleType.Recording, 1)]
    public partial class ConsentStatement : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSmyHearing.STSmyHearingRepository repository.
        /// </summary>
        public static STSmyHearing.STSmyHearingRepository repo = STSmyHearing.STSmyHearingRepository.Instance;

        static ConsentStatement instance = new ConsentStatement();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConsentStatement()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConsentStatement Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Click on "Start" and enter the code
            Report.Log(ReportLevel.Info, "Section", "Step## Click on \"Start\" and enter the code", new RecordItemIndex(0));
            
            TapOn("Start");
            Delay.Milliseconds(0);
            
            EnterCode();
            Delay.Milliseconds(0);
            
            ValidateContents("Consent Statement;Privacy policy;Terms and conditions;Accept");
            Delay.Milliseconds(0);
            
            // Validation## The Consent Statement should be shown. Below there should be privacy policy and Terms & conditions. There should be a accept button Please write a comment or attach a screenshot.
            Report.Log(ReportLevel.Info, "Section", "Validation## The Consent Statement should be shown. Below there should be privacy policy and Terms & conditions. There should be a accept button Please write a comment or attach a screenshot.", new RecordItemIndex(4));
            
            // Step## Click on "Accept" button.
            Report.Log(ReportLevel.Info, "Section", "Step## Click on \"Accept\" button.", new RecordItemIndex(5));
            
            TapOn("Accept");
            Delay.Milliseconds(0);
            
            // Validation## The user goes to the next Screen in onboarding. Please write a comment or attach a screenshot.
            Report.Log(ReportLevel.Info, "Section", "Validation## The user goes to the next Screen in onboarding. Please write a comment or attach a screenshot.", new RecordItemIndex(7));
            
            ValidateContents("Pair your hearing aids;Start");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
