///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSmyHearing.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NonRiskRelatedInfo recording.
    /// </summary>
    [TestModule("ed7abb22-c19d-4716-9be2-ba5a1fa70d12", ModuleType.Recording, 1)]
    public partial class NonRiskRelatedInfo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSmyHearing.STSmyHearingRepository repository.
        /// </summary>
        public static STSmyHearing.STSmyHearingRepository repo = STSmyHearing.STSmyHearingRepository.Instance;

        static NonRiskRelatedInfo instance = new NonRiskRelatedInfo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NonRiskRelatedInfo()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NonRiskRelatedInfo Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            TapOnHome();
            Delay.Milliseconds(0);
            
            TapOn("My Hearing Aid");
            Delay.Milliseconds(0);
            
            TapOn("User Guide");
            Delay.Milliseconds(0);
            
            ValidateActionBarTitle("User Guide");
            Delay.Milliseconds(0);
            
            TapOn("Imprint");
            Delay.Milliseconds(0);
            
            TapOn("Imprint");
            Delay.Milliseconds(0);
            
            ValidateActionBarTitle("Imprint");
            Delay.Milliseconds(0);
            
            SwipePageVerticle(ValueConverter.ArgumentFromString<int>("count", "3"), ValueConverter.ArgumentFromString<double>("startY", "0.6"), ValueConverter.ArgumentFromString<double>("endY", "0.2"), ValueConverter.ArgumentFromString<bool>("takeScreenshot", "True"));
            Delay.Milliseconds(0);
            
            ValidateContentsWithDesc("Sivantos Pte. Ltd.;28 Ayer Rajah Crescent #06-08;Singapore 139959;Phone:+65 6370 9666;Fax:+65 6773 8070;apps@sivantos.com;RCB No. 198600657G", ValueConverter.ArgumentFromString<bool>("takeScreenshot", "False"));
            Delay.Milliseconds(0);
            
            ValidateContentsWithDesc("Trademark License of Siemens AG", ValueConverter.ArgumentFromString<bool>("takeScreenshot", "False"));
            Delay.Milliseconds(0);
            
            ValidateContentsWithDesc("Sivantos Pte. Ltd. 2017 All Rights Reserved", ValueConverter.ArgumentFromString<bool>("takeScreenshot", "False"));
            Delay.Milliseconds(0);
            
            ValidateContentsWithDesc("Made in Germany", ValueConverter.ArgumentFromString<bool>("takeScreenshot", "False"));
            Delay.Milliseconds(0);
            
            ValidateContentsWithDesc("CE0123", ValueConverter.ArgumentFromString<bool>("takeScreenshot", "False"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
