///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSmyHearing.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The POC1 recording.
    /// </summary>
    [TestModule("75fd3119-a461-4895-b472-fa33e10ad1a8", ModuleType.Recording, 1)]
    public partial class POC1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSmyHearing.STSmyHearingRepository repository.
        /// </summary>
        public static STSmyHearing.STSmyHearingRepository repo = STSmyHearing.STSmyHearingRepository.Instance;

        static POC1 instance = new POC1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public POC1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static POC1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            TapOnHome();
            Delay.Milliseconds(0);
            
            TapOn("My Hearing Aid");
            Delay.Milliseconds(0);
            
            TapOn("User Guide");
            Delay.Milliseconds(0);
            
            ValidateActionBarTitle("User Guide");
            Delay.Milliseconds(0);
            
            TapOn("App Info");
            Delay.Milliseconds(0);
            
            ValidateActionBarTitle("App Info");
            Delay.Milliseconds(0);
            
            ValidateContents("Intended Use;The myHearing app is a tool whereby the patient can adjust comfort functions of a hearing aid, within a framework given by a hearing care professional, e.g., ENT doctor, audiologist or acoustician. It also enables the hearing care professional to remotely personalise the hearing instruments sound within a given framework.");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
