///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSiOSTouchControl.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MuteFunction recording.
    /// </summary>
    [TestModule("8c447c0a-7e7d-472d-9222-6dd7a83b130c", ModuleType.Recording, 1)]
    public partial class MuteFunction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSiOSTouchControl.STSiOSTouchControlRepository repository.
        /// </summary>
        public static STSiOSTouchControl.STSiOSTouchControlRepository repo = STSiOSTouchControl.STSiOSTouchControlRepository.Instance;

        static MuteFunction instance = new MuteFunction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MuteFunction()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MuteFunction Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Stepp## Open Touch control and changethe program
            Report.Log(ReportLevel.Info, "Section", "Stepp## Open Touch control and changethe program", new RecordItemIndex(0));
            
            TapOnProgram();
            Delay.Milliseconds(0);
            
            TapOn("Program 2");
            Delay.Milliseconds(0);
            
            // Validation## User should be able to change the programs
            Report.Log(ReportLevel.Info, "Section", "Validation## User should be able to change the programs", new RecordItemIndex(3));
            
            ValidateContents("Program 2");
            Delay.Milliseconds(0);
            
            ValidateMuteUnmute(ValueConverter.ArgumentFromString<bool>("muteUnmute", "True"));
            Delay.Milliseconds(0);
            
            // Step## Click on Mute icon
            Report.Log(ReportLevel.Info, "Section", "Step## Click on Mute icon", new RecordItemIndex(6));
            
            TapOnMuteUnmute();
            Delay.Milliseconds(0);
            
            // Validation## A spinner is shown and HI sound is muted according to application control.
            Report.Log(ReportLevel.Info, "Section", "Validation## A spinner is shown and HI sound is muted according to application control.", new RecordItemIndex(8));
            
            ValidateMuteUnmute(ValueConverter.ArgumentFromString<bool>("muteUnmute", "False"));
            Delay.Milliseconds(0);
            
            // Step## Change the program The program
            Report.Log(ReportLevel.Info, "Section", "Step## Change the program The program", new RecordItemIndex(10));
            
            TapOnProgram();
            Delay.Milliseconds(0);
            
            TapOn("Program 1");
            Delay.Milliseconds(0);
            
            // Validation## The program is changed successfully. Mute functionality should not be retained
            Report.Log(ReportLevel.Info, "Section", "Validation## The program is changed successfully. Mute functionality should not be retained", new RecordItemIndex(13));
            
            ValidateMuteUnmute(ValueConverter.ArgumentFromString<bool>("muteUnmute", "True"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
