///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSiOSTouchControl.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TinnitusMixedMode recording.
    /// </summary>
    [TestModule("c7f37ce8-e987-4ca2-94f6-4df8e2a6587c", ModuleType.Recording, 1)]
    public partial class TinnitusMixedMode : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSiOSTouchControl.STSiOSTouchControlRepository repository.
        /// </summary>
        public static STSiOSTouchControl.STSiOSTouchControlRepository repo = STSiOSTouchControl.STSiOSTouchControlRepository.Instance;

        static TinnitusMixedMode instance = new TinnitusMixedMode();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TinnitusMixedMode()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TinnitusMixedMode Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Go to programs list and select Tinnitus program
            Report.Log(ReportLevel.Info, "Section", "Step## Go to programs list and select Tinnitus program", new RecordItemIndex(0));
            
            TapOnProgram();
            Delay.Milliseconds(0);
            
            ValidateContents("Tinnitus");
            Delay.Milliseconds(0);
            
            TapOn("Tinnitus");
            Delay.Milliseconds(0);
            
            // Validation## The Tinnitus program should be in mixed mode.Slider for volume command and Therapy signal should be present
            Report.Log(ReportLevel.Info, "Section", "Validation## The Tinnitus program should be in mixed mode.Slider for volume command and Therapy signal should be present", new RecordItemIndex(4));
            
            ValidateContents("Tinnitus;Therapy signal");
            Delay.Milliseconds(0);
            
            ValidateTinnitusMixedMode();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
