///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSiOSTouchControl.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UsageStatistics recording.
    /// </summary>
    [TestModule("a2bcdebc-f888-41d6-9f0e-d6a8a946bc76", ModuleType.Recording, 1)]
    public partial class UsageStatistics : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSiOSTouchControl.STSiOSTouchControlRepository repository.
        /// </summary>
        public static STSiOSTouchControl.STSiOSTouchControlRepository repo = STSiOSTouchControl.STSiOSTouchControlRepository.Instance;

        static UsageStatistics instance = new UsageStatistics();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UsageStatistics()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UsageStatistics Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Open the Application and Press Settings/More button .
            Report.Log(ReportLevel.Info, "Section", "Step## Open the Application and Press Settings/More button .", new RecordItemIndex(0));
            
            TapOnSettings();
            Delay.Milliseconds(0);
            
            // Validation## More screen is opened. Usage Statistics is ON by default.
            Report.Log(ReportLevel.Info, "Section", "Validation## More screen is opened. Usage Statistics is ON by default.", new RecordItemIndex(2));
            
            ValidateUsageStatistics(ValueConverter.ArgumentFromString<bool>("isON", "True"));
            Delay.Milliseconds(0);
            
            // Step## Switch statistics toggle to OFF
            Report.Log(ReportLevel.Info, "Section", "Step## Switch statistics toggle to OFF", new RecordItemIndex(4));
            
            SwitchUsageStatistics(ValueConverter.ArgumentFromString<bool>("on", "False"));
            Delay.Milliseconds(0);
            
            // Validation## Settings screen is opened and following controls are displayed:Back button, Sound Balance, Sound Settings, Setup, Advanced Setup, Language, Rate our App, Usage statistics, Help, Imprint, App Version
            Report.Log(ReportLevel.Info, "Section", "Validation## Settings screen is opened and following controls are displayed:Back button, Sound Balance, Sound Settings, Setup, Advanced Setup, Language, Rate our App, Usage statistics, Help, Imprint, App Version", new RecordItemIndex(6));
            
            ValidateUsageStatistics(ValueConverter.ArgumentFromString<bool>("isON", "False"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
