///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace STSiOSMFApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the STSiOSMFAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("11dc7510-eebc-48c7-83a1-c68d85679829")]
    public partial class STSiOSMFAppRepository : RepoGenBaseFolder
    {
        static STSiOSMFAppRepository instance = new STSiOSMFAppRepository();

        /// <summary>
        /// Gets the singleton class instance representing the STSiOSMFAppRepository element repository.
        /// </summary>
        [RepositoryFolder("11dc7510-eebc-48c7-83a1-c68d85679829")]
        public static STSiOSMFAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public STSiOSMFAppRepository() 
            : base("STSiOSMFAppRepository", "/", null, 0, false, "11dc7510-eebc-48c7-83a1-c68d85679829", ".\\RepositoryImages\\STSiOSMFAppRepository11dc7510.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("11dc7510-eebc-48c7-83a1-c68d85679829")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class STSiOSMFAppRepositoryFolders
    {
    }
#pragma warning restore 0436
}