///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace STSAndBasic
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the STSAndBasicRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("be2fa462-7d5d-4acb-97d9-44e086031045")]
    public partial class STSAndBasicRepository : RepoGenBaseFolder
    {
        static STSAndBasicRepository instance = new STSAndBasicRepository();

        /// <summary>
        /// Gets the singleton class instance representing the STSAndBasicRepository element repository.
        /// </summary>
        [RepositoryFolder("be2fa462-7d5d-4acb-97d9-44e086031045")]
        public static STSAndBasicRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public STSAndBasicRepository() 
            : base("STSAndBasicRepository", "/", null, 0, false, "be2fa462-7d5d-4acb-97d9-44e086031045", ".\\RepositoryImages\\STSAndBasicRepositorybe2fa462.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("be2fa462-7d5d-4acb-97d9-44e086031045")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class STSAndBasicRepositoryFolders
    {
    }
#pragma warning restore 0436
}