///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndBasic.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AppInfo recording.
    /// </summary>
    [TestModule("5604ab5c-6cfd-4fc4-9e44-64ac27efb435", ModuleType.Recording, 1)]
    public partial class AppInfo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndBasic.STSAndBasicRepository repository.
        /// </summary>
        public static STSAndBasic.STSAndBasicRepository repo = STSAndBasic.STSAndBasicRepository.Instance;

        static AppInfo instance = new AppInfo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AppInfo()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AppInfo Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Open the app and tap on the info icon
            Report.Log(ReportLevel.Info, "Section", "Step## Open the app and tap on the info icon", new RecordItemIndex(0));
            
            ClickInfoButton();
            Delay.Milliseconds(0);
            
            VerifyActionBarTitle("Info");
            Delay.Milliseconds(0);
            
            // Step## Select the app info icon
            Report.Log(ReportLevel.Info, "Section", "Step## Select the app info icon", new RecordItemIndex(3));
            
            SelectPageFromInfo("App Info");
            Delay.Milliseconds(0);
            
            // Validation## Displays detail about the MobileFitting app along with a Update Hint - "Always use the latest available version of the app. Keep the operating system of your smartphone up to date"
            Report.Log(ReportLevel.Info, "Section", "Validation## Displays detail about the MobileFitting app along with a Update Hint - \"Always use the latest available version of the app. Keep the operating system of your smartphone up to date\"", new RecordItemIndex(5));
            
            ValidateInfoPage("App Info");
            Delay.Milliseconds(0);
            
            ValidateContents("Intended Use;Important Information;Control Signals;Pure Tone Estimation;Updates;Always use the latest available version of the app. Keep the operating system of your mobile device up to date.");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
