///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndBasic.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DuplicateCustomer recording.
    /// </summary>
    [TestModule("60918b70-34aa-4152-bd31-01d4fb0adaff", ModuleType.Recording, 1)]
    public partial class DuplicateCustomer : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndBasic.STSAndBasicRepository repository.
        /// </summary>
        public static STSAndBasic.STSAndBasicRepository repo = STSAndBasic.STSAndBasicRepository.Instance;

        static DuplicateCustomer instance = new DuplicateCustomer();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DuplicateCustomer()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DuplicateCustomer Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Open the app and goto New.Create a new customer - enter last, first name. Hit Continue
            Report.Log(ReportLevel.Info, "Section", "Step## Open the app and goto New.Create a new customer - enter last, first name. Hit Continue", new RecordItemIndex(0));
            
            CreatePatient("Customer", "Duplicate");
            Delay.Milliseconds(0);
            
            SelectCustomerContinue();
            Delay.Milliseconds(0);
            
            // Validation## Customer is created
            Report.Log(ReportLevel.Info, "Section", "Validation## Customer is created", new RecordItemIndex(3));
            
            VerifyActionBarTitle("Customer, Duplicate");
            Delay.Milliseconds(0);
            
            ValidateContents("Enter Audiogram;Select Hearing Aid;Select Sound Profile;Fit Coupling;Assemble Hearing Aid;Send Data to Hearing Aid;Check Sound Comfort");
            Delay.Milliseconds(0);
            
            // Step## Press Back and select New Again - create a customer with same last, first name as previously entered -hit Continue
            Report.Log(ReportLevel.Info, "Section", "Step## Press Back and select New Again - create a customer with same last, first name as previously entered -hit Continue", new RecordItemIndex(6));
            
            BackAction();
            Delay.Milliseconds(0);
            
            CreatePatient("Customer", "Duplicate", "");
            Delay.Milliseconds(0);
            
            SelectCustomerContinue();
            Delay.Milliseconds(0);
            
            // Validation## On hitting Continue, alert "Please modify clients data to remove duplicates" is displayed.
            Report.Log(ReportLevel.Info, "Section", "Validation## On hitting Continue, alert \"Please modify clients data to remove duplicates\" is displayed.", new RecordItemIndex(10));
            
            ValidateALertMessage("Please modify the client data to remove duplicates.");
            Delay.Milliseconds(0);
            
            ClickOnAlertMessage("OK");
            Delay.Milliseconds(0);
            
            // Step## Create a new customer with same details as in step 3 but different dob, notes and existing audioram toggle status
            Report.Log(ReportLevel.Info, "Section", "Step## Create a new customer with same details as in step 3 but different dob, notes and existing audioram toggle status", new RecordItemIndex(13));
            
            CreatePatient("", "", "Jun_16_1955");
            Delay.Milliseconds(0);
            
            SelectCustomerContinue();
            Delay.Milliseconds(0);
            
            // Validation## Customer is created
            Report.Log(ReportLevel.Info, "Section", "Validation## Customer is created", new RecordItemIndex(16));
            
            VerifyActionBarTitle("Customer, Duplicate");
            Delay.Milliseconds(0);
            
            ValidateContents("Enter Audiogram;Select Hearing Aid;Select Sound Profile;Fit Coupling;Assemble Hearing Aid;Send Data to Hearing Aid;Check Sound Comfort");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
