///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndBasic.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TabDiscardCouplingSelection recording.
    /// </summary>
    [TestModule("d7a461c9-5c03-476c-8bbb-6133391c6f30", ModuleType.Recording, 1)]
    public partial class TabDiscardCouplingSelection : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndBasic.STSAndBasicRepository repository.
        /// </summary>
        public static STSAndBasic.STSAndBasicRepository repo = STSAndBasic.STSAndBasicRepository.Instance;

        static TabDiscardCouplingSelection instance = new TabDiscardCouplingSelection();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TabDiscardCouplingSelection()
        {
            H2 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TabDiscardCouplingSelection Instance
        {
            get { return instance; }
        }

#region Variables

        string _H2;

        /// <summary>
        /// Gets or sets the value of variable H2.
        /// </summary>
        [TestVariable("e15682a8-5f7f-46b7-bb58-5a0163dad748")]
        public string H2
        {
            get { return _H2; }
            set { _H2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step##  Pre-Condition - Initial setup and Access code setup is done. Customer created with audiogram configured
            Report.Log(ReportLevel.Info, "Section", "Step##  Pre-Condition - Initial setup and Access code setup is done. Customer created with audiogram configured", new RecordItemIndex(0));
            
            TapOnSettings("Tap on 'Settings'");
            Delay.Milliseconds(0);
            
            SwitchSettingUseMold(ValueConverter.ArgumentFromString<bool>("YesNo", "True"));
            Delay.Milliseconds(0);
            
            CreatePatient("CouplingSelection", "Discard");
            Delay.Milliseconds(0);
            
            SelectCustomerContinue();
            Delay.Milliseconds(0);
            
            CloseApp();
            Delay.Milliseconds(0);
            
            // Step## Open the app, goto List. Select the existing customer
            //Report.Log(ReportLevel.Info, "Section", "Step## Open the app, goto List. Select the existing customer", new RecordItemIndex(6));
            
            StartApp();
            Delay.Milliseconds(0);
            
            SearchCustomer("Discard");
            Delay.Milliseconds(0);
            
            SelectCustomer("CouplingSelection", "Discard");
            Delay.Milliseconds(0);
            
            // Validation##Opens the overview screen with Enter Audiogram step highlighted
            Report.Log(ReportLevel.Info, "Section", "Validation##Opens the overview screen with Enter Audiogram step highlighted", new RecordItemIndex(10));
            
            VerifyActionBarTitle("CouplingSelection, Discard");
            Delay.Milliseconds(0);
            
            VerifyTextHighlighted("Enter Audiogram");
            Delay.Milliseconds(0);
            
            // Step## Enter (Right), @500Hz, @1kHz, @2kHz, @4kHz.Press Done
            Report.Log(ReportLevel.Info, "Section", "Step## Enter (Right), @500Hz, @1kHz, @2kHz, @4kHz.Press Done", new RecordItemIndex(13));
            
            TapOn("Enter Audiogram");
            Delay.Milliseconds(0);
            
            DrawAudiogramPoints("Right", "500,90;1000,90;2000,90;4000,90");
            Delay.Milliseconds(0);
            
            TabTapOnRightButton("Click on 'Done'");
            Delay.Milliseconds(0);
            
            // Validation## Popup Appears as "Do you want to enter values for left ear side too?"
            Report.Log(ReportLevel.Info, "Section", "Validation## Popup Appears as \"Do you want to enter values for left ear side too?\"", new RecordItemIndex(17));
            
            ValidateALertMessage("Do you want to enter values for the \"left\" ear side too?");
            Delay.Milliseconds(0);
            
            // Step## Press No when popup appears.
            Report.Log(ReportLevel.Info, "Section", "Step## Press No when popup appears.", new RecordItemIndex(19));
            
            ClickOnAlertMessage("No");
            Delay.Milliseconds(0);
            
            // Validation## Returns to the overview screen with HI-Type : Run SP, coupling : Custom mold and Cluster : P5 and Send data to HI
            Report.Log(ReportLevel.Info, "Section", "Validation## Returns to the overview screen with HI-Type : Run SP, coupling : Custom mold and Cluster : P5 and Send data to HI", new RecordItemIndex(21));
            
            ValidateMonauralHISelected(H2, "Right");
            Delay.Milliseconds(0);
            
            ValidateMonauralCouplingSelected("Custom Mold", "Right");
            Delay.Milliseconds(0);
            
            ValidateMonauralClusterSelected("P5", "Right");
            Delay.Milliseconds(0);
            
            VerifyTextHighlighted("Send Data to Hearing Aid");
            Delay.Milliseconds(0);
            
            // Step## Reselect HI to Run SP and select coupling to tip
            Report.Log(ReportLevel.Info, "Section", "Step## Reselect HI to Run SP and select coupling to tip", new RecordItemIndex(26));
            
            TapOn(H2);
            Delay.Milliseconds(0);
            
            TapOn("Fit right ear with hearing aid");
            Delay.Milliseconds(0);
            
            TapOnWithContentDesc(H2);
            Delay.Milliseconds(0);
            
            TapOn("Tip");
            Delay.Milliseconds(0);
            
            // Validation## Coupling type should be changed to tip in overview screen and cluster should not be changed as HI is not changed.
            Report.Log(ReportLevel.Info, "Section", "Validation## Coupling type should be changed to tip in overview screen and cluster should not be changed as HI is not changed.", new RecordItemIndex(31));
            
            ValidateMonauralCouplingSelected("Tip", "Right");
            Delay.Milliseconds(0);
            
            ValidateMonauralClusterSelected("P5", "Right");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
