///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndBasic.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TabEnterValidationCodeDone recording.
    /// </summary>
    [TestModule("adbc064a-28db-40a3-ba49-2d75e3f1fef0", ModuleType.Recording, 1)]
    public partial class TabEnterValidationCodeDone : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndBasic.STSAndBasicRepository repository.
        /// </summary>
        public static STSAndBasic.STSAndBasicRepository repo = STSAndBasic.STSAndBasicRepository.Instance;

        static TabEnterValidationCodeDone instance = new TabEnterValidationCodeDone();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TabEnterValidationCodeDone()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TabEnterValidationCodeDone Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Open the app and Accept and Continue the initial start up text
            Report.Log(ReportLevel.Info, "Section", "Step## Open the app and Accept and Continue the initial start up text", new RecordItemIndex(0));
            
            StartApp();
            Delay.Milliseconds(0);
            
            AcceptAndContinueWelcomeScreen();
            Delay.Milliseconds(0);
            
            VerifyActionBarTitle("Country");
            Delay.Milliseconds(0);
            
            SelectCountry("India");
            Delay.Milliseconds(0);
            
            // Step## Select the country location & click on done
            Report.Log(ReportLevel.Info, "Section", "Step## Select the country location & click on done", new RecordItemIndex(5));
            
            TapOnRightButton("Click on 'Done'");
            Delay.Milliseconds(0);
            
            VerifyActionBarTitle("Access Code");
            Delay.Milliseconds(0);
            
            // Step## Enter correct code and press Done
            Report.Log(ReportLevel.Info, "Section", "Step## Enter correct code and press Done", new RecordItemIndex(8));
            
            EnterCorrectCode();
            Delay.Milliseconds(0);
            
            DoneAuthenticationScreen();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(11));
            Delay.Duration(3000, false);
            
            // Validation## Code entered successfully message shown with option to Continue
            Report.Log(ReportLevel.Info, "Section", "Validation## Code entered successfully message shown with option to Continue", new RecordItemIndex(12));
            
            ValidateContentsContains("Code entered successfully.", ValueConverter.ArgumentFromString<bool>("isFound", "True"));
            Delay.Milliseconds(0);
            
            // Step## Tap Continue
            Report.Log(ReportLevel.Info, "Section", "Step## Tap Continue", new RecordItemIndex(14));
            
            TapContinue();
            Delay.Milliseconds(0);
            
            // Validation## Returns to Mold usage screen
            Report.Log(ReportLevel.Info, "Section", "Validation## Returns to Mold usage screen", new RecordItemIndex(16));
            
            VerifyActionBarTitle("Custom Ear Molds");
            Delay.Milliseconds(0);
            
            TapContinue();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
