///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndBasic.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TabEnablingDisabling recording.
    /// </summary>
    [TestModule("bad109c3-26a3-43a2-8096-12e40910da08", ModuleType.Recording, 1)]
    public partial class TabEnablingDisabling : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndBasic.STSAndBasicRepository repository.
        /// </summary>
        public static STSAndBasic.STSAndBasicRepository repo = STSAndBasic.STSAndBasicRepository.Instance;

        static TabEnablingDisabling instance = new TabEnablingDisabling();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TabEnablingDisabling()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TabEnablingDisabling Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Pre-condition - Initial setup is done
            Report.Log(ReportLevel.Info, "Section", "Step## Pre-condition - Initial setup is done", new RecordItemIndex(0));
            
            StartApp();
            Delay.Milliseconds(0);
            
            AcceptAndContinueWelcomeScreen();
            Delay.Milliseconds(0);
            
            VerifyActionBarTitle("Country");
            Delay.Milliseconds(0);
            
            // Step## Select the country and click on done button
            Report.Log(ReportLevel.Info, "Section", "Step## Select the country and click on done button", new RecordItemIndex(4));
            
            TapOnRightButton("Click on 'Done'");
            Delay.Milliseconds(0);
            
            EnterCorrectCode();
            Delay.Milliseconds(0);
            
            DoneAuthenticationScreen();
            Delay.Milliseconds(0);
            
            ContinueValidationScreen();
            Delay.Milliseconds(0);
            
            ContinueCustomerEarMoldScreen();
            Delay.Milliseconds(0);
            
            //SwitchToChooseHI();
            //Delay.Milliseconds(0);
            
            CloseApp();
            Delay.Milliseconds(0);
            
            // Step## Open the app
            Report.Log(ReportLevel.Info, "Section", "Step## Open the app", new RecordItemIndex(12));
            
            StartApp();
            Delay.Milliseconds(0);
            
            // Step## Press the settings icon
            Report.Log(ReportLevel.Info, "Section", "Step## Press the settings icon", new RecordItemIndex(14));
            
            TapOnSettings("Tap on Settings icon");
            Delay.Milliseconds(0);
            
            // Validation## Setting screen is opened. Usage statistics toggle is activated (ON) by default.
            Report.Log(ReportLevel.Info, "Section", "Validation## Setting screen is opened. Usage statistics toggle is activated (ON) by default.", new RecordItemIndex(16));
            
            VerifyActionBarTitle("Settings");
            Delay.Milliseconds(0);
            
            ValidateUsageStatistics(ValueConverter.ArgumentFromString<bool>("isON", "True"));
            Delay.Milliseconds(0);
            
            // Step## Turn the toggle OFF
            Report.Log(ReportLevel.Info, "Section", "Step## Turn the toggle OFF", new RecordItemIndex(19));
            
            SwitchUsageStatistics(ValueConverter.ArgumentFromString<bool>("on", "False"));
            Delay.Milliseconds(0);
            
            // Validation## The tracking is deactivated. The toggle is set to off state
            Report.Log(ReportLevel.Info, "Section", "Validation## The tracking is deactivated. The toggle is set to off state", new RecordItemIndex(21));
            
            ValidateUsageStatistics(ValueConverter.ArgumentFromString<bool>("isON", "False"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
