///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndBasic.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TabRecommendationOfHIsWithAudiogram recording.
    /// </summary>
    [TestModule("7cb4755b-ca7a-4a92-a1da-33632aa6b11a", ModuleType.Recording, 1)]
    public partial class TabRecommendationOfHIsWithAudiogram : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndBasic.STSAndBasicRepository repository.
        /// </summary>
        public static STSAndBasic.STSAndBasicRepository repo = STSAndBasic.STSAndBasicRepository.Instance;

        static TabRecommendationOfHIsWithAudiogram instance = new TabRecommendationOfHIsWithAudiogram();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TabRecommendationOfHIsWithAudiogram()
        {
            LastName = "RunP";
            FirstName = "WithAudi";
            AUPoints = "500,40;1000,45;2000,50;4000,60";
            HIName = "Run P";
            Coupling = "Tip";
            Cluster = "P1";
            isAlert = "False";
            isCouplingAvailable = "False";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TabRecommendationOfHIsWithAudiogram Instance
        {
            get { return instance; }
        }

#region Variables

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("7e097805-f8f7-4132-bfff-e819b61fb793")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("f4adbb5f-8d5d-4976-b09d-1ab741de5ec7")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _AUPoints;

        /// <summary>
        /// Gets or sets the value of variable AUPoints.
        /// </summary>
        [TestVariable("67a338a7-0654-4e35-9018-9ead059d63e8")]
        public string AUPoints
        {
            get { return _AUPoints; }
            set { _AUPoints = value; }
        }

        string _HIName;

        /// <summary>
        /// Gets or sets the value of variable HIName.
        /// </summary>
        [TestVariable("379e69e2-f545-447e-9114-589435c88f74")]
        public string HIName
        {
            get { return _HIName; }
            set { _HIName = value; }
        }

        string _Coupling;

        /// <summary>
        /// Gets or sets the value of variable Coupling.
        /// </summary>
        [TestVariable("867a97c9-2c24-4f20-b432-1eb7697a1b65")]
        public string Coupling
        {
            get { return _Coupling; }
            set { _Coupling = value; }
        }

        string _Cluster;

        /// <summary>
        /// Gets or sets the value of variable Cluster.
        /// </summary>
        [TestVariable("fb830eac-baff-4fda-8f77-b5d84cf631aa")]
        public string Cluster
        {
            get { return _Cluster; }
            set { _Cluster = value; }
        }

        string _isAlert;

        /// <summary>
        /// Gets or sets the value of variable isAlert.
        /// </summary>
        [TestVariable("945fcdd2-f929-4123-aa85-0b64ca05e6a1")]
        public string isAlert
        {
            get { return _isAlert; }
            set { _isAlert = value; }
        }

        string _isCouplingAvailable;

        /// <summary>
        /// Gets or sets the value of variable isCouplingAvailable.
        /// </summary>
        [TestVariable("75864700-1b67-4b4e-920c-154d6e6741ab")]
        public string isCouplingAvailable
        {
            get { return _isCouplingAvailable; }
            set { _isCouplingAvailable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Step##  Pre-Condition - Initial setup and Access code setup is done. Customer created with audiogram configured
            //Report.Log(ReportLevel.Info, "Section", "Step##  Pre-Condition - Initial setup and Access code setup is done. Customer created with audiogram configured", new RecordItemIndex(0));
            
            TapOnSettings("Tap on 'Settings'");
            
            SwitchSettingUseMold(ValueConverter.ArgumentFromString<bool>("YesNo", "True"));
            
            CreatePatient(LastName, FirstName);
            
            SelectCustomerContinue();
            
            CloseApp();
            
            // Step## Open the app, goto List. Select the existing customer
            Report.Log(ReportLevel.Info, "Section", "Step## Open the app, goto List. Select the existing customer", new RecordItemIndex(6));
            
            StartApp();
            
            SearchCustomer(FirstName);
            
            SelectCustomer(LastName, FirstName);
            
            // Step## Enter (Right), @500Hz, @1kHz, @2kHz, @4kHz.Press Done
            Report.Log(ReportLevel.Info, "Section", "Step## Enter (Right), @500Hz, @1kHz, @2kHz, @4kHz.Press Done", new RecordItemIndex(10));
            
            TapEnterAudiogram();
            
            DrawAudiogramPoints("Right", AUPoints);
            
            TabTapOnRightButton("Click on 'Done'");
            
            ValidateALertMessage("Do you want to enter values for the \"left\" ear side too?");
            
            ClickOnAlertMessage("No");
            
            CloseApp();
            
            StartApp();
            
            SearchCustomer(FirstName);
            
            SelectCustomer(LastName, FirstName);
            
            // Validation## Audiogram is saved - Recommendation should be @HI , @coupling type & @Cluster
            Report.Log(ReportLevel.Info, "Section", "Validation## Audiogram is saved - Recommendation should be @HI , @coupling type & @Cluster", new RecordItemIndex(20));
            
            TapOnMonauralHI("Tap on MonauralHI");
            
            TapOn("Fit right ear with hearing aid");
            
            TapOnWithContentDesc(HIName);
            
            SelectCouplingIfAvailable(ValueConverter.ArgumentFromString<bool>("isCouplingAvailable", isCouplingAvailable), Coupling);
            
            ValidateMonauralHISelected(HIName, "Right");
            
            ValidateMonauralCouplingSelected(Coupling, "Right");
            
            ValidateMonauralClusterSelected(Cluster, "Right");
            
            // Step## Press Send data to HI and Connect to HI
            Report.Log(ReportLevel.Info, "Section", "Step## Press Send data to HI and Connect to HI", new RecordItemIndex(28));
            
            // Validation## Attention message is displayed as Selected sound profile has high amplification output.
            Report.Log(ReportLevel.Info, "Section", "Validation## Attention message is displayed as Selected sound profile has high amplification output.", new RecordItemIndex(29));
            
            ConnectHI();
            
            ValidateALertMessage("Selected Sound Profile has high amplification output.", ValueConverter.ArgumentFromString<bool>("isAlert", isAlert));
            
            ConfirmationToneYes();
            
            // Step## Press Sound Comfort and Press OK
            Report.Log(ReportLevel.Info, "Section", "Step## Press Sound Comfort and Press OK", new RecordItemIndex(33));
            
            TapOn("Check Sound Comfort");
            
            SoundComfortOk();
            
            // Step## Close session.
            Report.Log(ReportLevel.Info, "Section", "Step## Close session.", new RecordItemIndex(36));
            
            CloseSession();
            
            // Step## Reselect same customer
            Report.Log(ReportLevel.Info, "Section", "Step## Reselect same customer", new RecordItemIndex(38));
            
            SearchCustomer(FirstName);
            
            SelectCustomer(LastName, FirstName);
            
            // Step## Press audiogram tab and open the edit screen
            Report.Log(ReportLevel.Info, "Section", "Step## Press audiogram tab and open the edit screen", new RecordItemIndex(41));
            
            EditAudiogram();
            
            // Step## Enter (Left), @500Hz, @1kHz, @2kHz, @4kHz.Press Done.
            Report.Log(ReportLevel.Info, "Section", "Step## Enter (Left), @500Hz, @1kHz, @2kHz, @4kHz.Press Done.", new RecordItemIndex(43));
            
            DrawAudiogramPoints("Left", AUPoints);
            
            TabTapOnRightButton("Click on 'Done'");
            
            ContinueWithLeftEar();
            
            ValidateBinauralHISelected(HIName, "Right");
            
            ValidateBinauralCouplingSelected(Coupling, "Right");
            
            ValidateBinauralClusterSelected(Cluster, "Right");
            
            TapOnBinauralHI("Tap On BinauralHI", "Left");
            
            TapOnWithContentDesc(HIName);
            
            SelectCouplingIfAvailable(ValueConverter.ArgumentFromString<bool>("isCouplingAvailable", isCouplingAvailable), Coupling);
            
            ValidateBinauralHISelected(HIName, "Left");
            
            ValidateBinauralCouplingSelected(Coupling, "Left");
            
            ValidateBinauralClusterSelected(Cluster, "Left");
            
            // Step## Press Send data to HI and Connect to HI for Left side
            Report.Log(ReportLevel.Info, "Section", "Step## Press Send data to HI and Connect to HI for Left side", new RecordItemIndex(56));
            
            // Validation## warning message is displayed as Selected sound profile has high amplification output.
            Report.Log(ReportLevel.Info, "Section", "Validation## warning message is displayed as Selected sound profile has high amplification output.", new RecordItemIndex(57));
            
            ConnectHI();
            
            ValidateALertMessage("Selected Sound Profile has high amplification output.", ValueConverter.ArgumentFromString<bool>("isAlert", isAlert));
            
            //ValidateALertMessage("Please switch OFF hearing aid for right ear side.");
            
            ClickOnAlertMessage("OK");
            
            ConfirmationToneYes();
            
            ClickOnAlertMessage("OK");
            
            SelectPage("Check Sound Comfort");
            
            // Step## Press Sound Comfort and Press OK
            Report.Log(ReportLevel.Info, "Section", "Step## Press Sound Comfort and Press OK", new RecordItemIndex(65));
            
            SoundComfortOk();
            
            // Step## Press Close session
            Report.Log(ReportLevel.Info, "Section", "Step## Press Close session", new RecordItemIndex(67));
            
            CloseSession();
            
            // Validation## Returns to Customer list screen
            Report.Log(ReportLevel.Info, "Section", "Validation## Returns to Customer list screen", new RecordItemIndex(69));
            
            VerifyActionBarTitle("Client List");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
