///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndTouchControl.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InterfaceLanguages recording.
    /// </summary>
    [TestModule("cd39ab2a-239d-4c59-8490-cdc8fad54627", ModuleType.Recording, 1)]
    public partial class InterfaceLanguages : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndTouchControl.STSAndTouchControlRepository repository.
        /// </summary>
        public static STSAndTouchControl.STSAndTouchControlRepository repo = STSAndTouchControl.STSAndTouchControlRepository.Instance;

        static InterfaceLanguages instance = new InterfaceLanguages();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InterfaceLanguages()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InterfaceLanguages Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Open touchControl app and check if application language is English
            Report.Log(ReportLevel.Info, "Section", "Step## Open touchControl app and check if application language is English", new RecordItemIndex(0));
            
            // Validation## Application is opened and application language is English.
            Report.Log(ReportLevel.Info, "Section", "Validation## Application is opened and application language is English.", new RecordItemIndex(1));
            
            TapOnSettings();
            Delay.Milliseconds(0);
            
            TapOn("Language");
            Delay.Milliseconds(0);
            
            ValidateTextSelected("English");
            Delay.Milliseconds(0);
            
            BackAction();
            Delay.Milliseconds(0);
            
            BackAction();
            Delay.Milliseconds(0);
            
            // Step## Open Settings
            Report.Log(ReportLevel.Info, "Section", "Step## Open Settings", new RecordItemIndex(7));
            
            TapOnSettings();
            Delay.Milliseconds(0);
            
            // Step## Select Language.
            Report.Log(ReportLevel.Info, "Section", "Step## Select Language.", new RecordItemIndex(9));
            
            TapOn("Language");
            Delay.Milliseconds(0);
            
            // Validation## Language screen is opened and available languages are listed.
            Report.Log(ReportLevel.Info, "Section", "Validation## Language screen is opened and available languages are listed.", new RecordItemIndex(11));
            
            ValidateContents("English;Deutsch;简体中文;繁體中文;Nederlands;Italiano;Español;Français;Norsk;Türkçe;Čeština;Polski;Português;Dansk;Svenska;Русский;한국어;Hungarian");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
