///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndTouchControl.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MFFlowLanguage recording.
    /// </summary>
    [TestModule("2b316d03-3e84-458b-a178-218d795a35d7", ModuleType.Recording, 1)]
    public partial class MFFlowLanguage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndTouchControl.STSAndTouchControlRepository repository.
        /// </summary>
        public static STSAndTouchControl.STSAndTouchControlRepository repo = STSAndTouchControl.STSAndTouchControlRepository.Instance;

        static MFFlowLanguage instance = new MFFlowLanguage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MFFlowLanguage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MFFlowLanguage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Pre-Condition - MF flow set up done
            Report.Log(ReportLevel.Info, "Section", "Pre-Condition - MF flow set up done", new RecordItemIndex(0));
            
            TapOnSettings();
            Delay.Milliseconds(0);
            
            TapOn("Setup");
            Delay.Milliseconds(0);
            
            TapOn("Manual Setup");
            Delay.Milliseconds(0);
            
            TapOn("Signia Run Products");
            Delay.Milliseconds(0);
            
            TapOn("Yes");
            Delay.Milliseconds(0);
            
            TapOn("Continue");
            Delay.Milliseconds(0);
            
            CloseApp();
            Delay.Milliseconds(0);
            
            // Step## Open application and Press Settings/ Menu button .
            Report.Log(ReportLevel.Info, "Section", "Step## Open application and Press Settings/ Menu button .", new RecordItemIndex(8));
            
            StartApp();
            Delay.Milliseconds(0);
            
            TapOnSettings();
            Delay.Milliseconds(0);
            
            // Step## Select Language
            Report.Log(ReportLevel.Info, "Section", "Step## Select Language", new RecordItemIndex(11));
            
            TapOn("Language");
            Delay.Milliseconds(0);
            
            // Validation## Language screen is opened and available languages are listed.
            Report.Log(ReportLevel.Info, "Section", "Validation## Language screen is opened and available languages are listed.", new RecordItemIndex(13));
            
            ValidateContents("English;Deutsch;简体中文;Nederlands;Italiano;Español;Français;Türkçe;Polski;Português;Svenska");
            Delay.Milliseconds(0);
            
            // Step## Select another language form the list
            Report.Log(ReportLevel.Info, "Section", "Step## Select another language form the list", new RecordItemIndex(15));
            
            TapOnWithSwipeDown("Deutsch");
            Delay.Milliseconds(0);
            
            // Validation## language is changed during the runtime and settings screen is displayed.
            Report.Log(ReportLevel.Info, "Section", "Validation## language is changed during the runtime and settings screen is displayed.", new RecordItemIndex(17));
            
            ValidateContents("Sendelautstärke;Einrichtung;Sprache;App bewerten");
            Delay.Milliseconds(0);
            
            // Step## Kill and re-launch the app
            Report.Log(ReportLevel.Info, "Section", "Step## Kill and re-launch the app", new RecordItemIndex(19));
            
            CloseApp();
            Delay.Milliseconds(0);
            
            StartApp();
            Delay.Milliseconds(0);
            
            TapOnSettings();
            Delay.Milliseconds(0);
            
            // Validation## Application is reopened in updated language.
            Report.Log(ReportLevel.Info, "Section", "Validation## Application is reopened in updated language.", new RecordItemIndex(23));
            
            ValidateContents("Sendelautstärke;Einrichtung;Sprache;App bewerten");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
