///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace STSAndTouchControl.TC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The QuitOptionOfTheApplication recording.
    /// </summary>
    [TestModule("46693b37-e3e3-4cf7-a63c-7da1838d2a55", ModuleType.Recording, 1)]
    public partial class QuitOptionOfTheApplication : ITestModule
    {
        /// <summary>
        /// Holds an instance of the STSAndTouchControl.STSAndTouchControlRepository repository.
        /// </summary>
        public static STSAndTouchControl.STSAndTouchControlRepository repo = STSAndTouchControl.STSAndTouchControlRepository.Instance;

        static QuitOptionOfTheApplication instance = new QuitOptionOfTheApplication();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public QuitOptionOfTheApplication()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static QuitOptionOfTheApplication Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Step## Launch the app after installation
            Report.Log(ReportLevel.Info, "Section", "Step## Launch the app after installation", new RecordItemIndex(0));
            
            StartApp();
            Delay.Milliseconds(0);
            
            // Validation## Welcome screen is shown
            Report.Log(ReportLevel.Info, "Section", "Validation## Welcome screen is shown", new RecordItemIndex(2));
            
            TapOn("Accept & Continue");
            Delay.Milliseconds(0);
            
            ValidateContents("Welcome to the touchControl app.");
            Delay.Milliseconds(0);
            
            // Step## Press back button of the smartphone/tablet
            Report.Log(ReportLevel.Info, "Section", "Step## Press back button of the smartphone/tablet", new RecordItemIndex(5));
            
            BackAction();
            Delay.Milliseconds(0);
            
            CloseApp();
            Delay.Milliseconds(0);
            
            // Step## Check if you quit from the application and opening it again touchControl app is opened and welcome screen is shown as a sign of quitting process.
            Report.Log(ReportLevel.Info, "Section", "Step## Check if you quit from the application and opening it again touchControl app is opened and welcome screen is shown as a sign of quitting process.", new RecordItemIndex(8));
            
            StartApp();
            Delay.Milliseconds(0);
            
            // Validation## Welcome screen is shown
            Report.Log(ReportLevel.Info, "Section", "Validation## Welcome screen is shown", new RecordItemIndex(10));
            
            ValidateContents("Welcome to the touchControl app.");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
